Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -10,7 +10,15 @@ jobs:
       uses: actions/checkout@v3
     - name: Setup Gradle
       uses: gradle/gradle-build-action@v2
-    - name: Build Project
-      run: gradle build
     - name: Run tests
       run: gradle test
+    - uses: actions/upload-artifact@v3
+      if: success() || failure() # always run even if the previous step fails
+      with:
+        name: mytest
+        path: '**/build/test-results/test/*.xml'
+    - uses: mikepenz/action-junit-report@v3
+      if: success() || failure() # always run even if the previous step fails
+      with:
+        report_paths: '**/build/test-results/test/*.xml'
+    
